kookmin-sw/capstone-2024-18

- src/main/java/capstone/facefriend/member/controller/FaceInfoController.java
- src/main/java/capstone/facefriend/member/domain/Member.java
- src/main/java/capstone/facefriend/member/service/BucketService.java
- src/main/java/capstone/facefriend/member/service/FaceInfoService.java
> 메서드 및 필드 이름 변경입니다.
> 메서드 및 필드 이름 변경입니다.
>
> style: 메서드 및 필드 이름 변경

- src/main/java/capstone/facefriend/auth/controller/dto/TokenResponse.java
- src/main/java/capstone/facefriend/auth/infrastructure/JwtProvider.java
- src/main/java/capstone/facefriend/auth/service/AuthService.java
- src/main/java/capstone/facefriend/member/controller/MemberController.java
- src/main/java/capstone/facefriend/member/service/MemberService.java
- src/main/java/capstone/facefriend/member/service/dto/member/SignupResponse.java
> fix: debug 를 위한 로직 및 DTO 수정

- src/main/java/capstone/facefriend/auth/infrastructure/JwtProvider.java
> Jwts.parser() deprecated 이슈 픽스
> fix: deprecated 된 Jwts.parser() 수정

- src/main/java/capstone/facefriend/bucket/BucketService.java
- src/main/java/capstone/facefriend/member/domain/resume/Resume.java
- src/main/java/capstone/facefriend/member/domain/resume/ResumeRepository.java
- src/main/java/capstone/facefriend/resume/controller/ResumeController.java
- src/main/java/capstone/facefriend/resume/exception/ResumeExceptionType.java
- src/main/java/capstone/facefriend/resume/service/ResumeService.java
> 없음
> 자기소개서 이미지를 업로드하지 않은 경우 빈 리스트를 반환하도록 수정했습니다.
> 자기소개서 카테고리를 최소 1개 이상 선택하지 않는 경우 예외를 던지도록 수정했습니다.
> 자기소개서 내용을 입력하지 않는 경우(빈 문자열, 공백문자 등) 예외를 던지도록 수정했습니다.
> 없음
> https://www.notion.so/Swagger-a83193a8deac47178ab4e464ca74408f
> 없음
> feat: 자기소개서 이미지 업로드하지 않으면 빈리스트 반환토록 수정

- src/main/java/capstone/facefriend/member/service/dto/faceInfo/FaceInfoResponse.java
> DTO 필드명 수정
> DTO 필드명 수정
> 없음
> 없음
> 없음
> 없음
> fix: DTO 필드명 수정

- src/main/java/capstone/facefriend/resume/domain/Resume.java
> Category 열거형 필드 수정
> Category 열거형 필드 수정
> 없음
> 없음
> 없음
> 없음
> fix: Category 열거형 필드 수정

- src/main/java/capstone/facefriend/resume/controller/ResumeController.java
> 자기소개서 디버깅
> 자기소개서 디버깅
> 없음
> 없음
> 없음
> fix: 자기소개서 디버깅

- src/main/java/capstone/facefriend/resume/controller/ResumeController.java
- src/main/java/capstone/facefriend/resume/domain/dto/ResumeGetResponse.java
- src/main/java/capstone/facefriend/resume/domain/dto/ResumePostPutResponse.java
> 자기소개서 디버깅 원복
> 자기소개서 디버깅 원복
> 없음
> 없음
> 없음
> fix: 자기소개서 디버깅 원복

- ai/face_generate.py
- ai/face_maker/DualStyleGAN/model/encoder/align_all_parallel.py
> feat: 배경지우기 기능 추가

- src/main/java/capstone/facefriend/resume/controller/ResumeController.java
- src/main/java/capstone/facefriend/resume/service/ResumeService.java
> 자기소개서 디버깅
> 자기소개서 디버깅
> 없음
> 없음
> 없음
> debug: 자기소개서 디버깅

- src/main/java/capstone/facefriend/resume/controller/ResumeController.java
- src/main/java/capstone/facefriend/resume/domain/dto/ResumePostRequest.java
- src/main/java/capstone/facefriend/resume/domain/dto/ResumeRequest.java
- src/main/java/capstone/facefriend/resume/service/ResumeService.java
> debug: 자기소개서 디버깅2

- src/main/java/capstone/facefriend/resume/domain/dto/ResumeRequest.java
- src/main/java/capstone/facefriend/resume/service/ResumeService.java
> 자기소개서 디버깅 완료
> 자기소개서 디버깅 완료
> 없음
> 없음
> 없음
> feat: 자기소개서 디버깅 완료, validation 수정

- src/main/java/capstone/facefriend/chat/config/ChatConfig.java
- src/main/java/capstone/facefriend/chat/config/RedisConfig.java
- src/main/java/capstone/facefriend/chat/controller/ChatRoomController.java
- src/main/java/capstone/facefriend/chat/controller/MessageController.java
- src/main/java/capstone/facefriend/chat/controller/interceptor/FilterChannelInterceptor.java
- src/main/java/capstone/facefriend/chat/domain/ChatRoomInfo.java
- src/main/java/capstone/facefriend/chat/domain/SocketInfo.java
- src/main/java/capstone/facefriend/chat/exception/ChatExceptionType.java
- src/main/java/capstone/facefriend/chat/repository/ChatMessageRepository.java
- src/main/java/capstone/facefriend/chat/repository/ChatRoomInfoRedisRepository.java
- src/main/java/capstone/facefriend/chat/repository/ChatRoomMemberRepository.java
- src/main/java/capstone/facefriend/chat/repository/SocketInfoRedisRepository.java
- src/main/java/capstone/facefriend/chat/service/ChatRoomService.java
- src/main/java/capstone/facefriend/chat/service/MessageService.java
- src/main/java/capstone/facefriend/chat/service/RedisSubscriber.java
- src/main/java/capstone/facefriend/chat/service/dto/chatroom/ChatRoomCloseResponse.java
- src/main/java/capstone/facefriend/chat/service/dto/chatroom/ChatRoomEnterResponse.java
- src/main/java/capstone/facefriend/chat/service/dto/chatroom/ChatRoomExitResponse.java
- src/main/java/capstone/facefriend/chat/service/dto/chatroom/ChatRoomHeartResponse.java
- src/main/java/capstone/facefriend/chat/service/dto/chatroom/ChatRoomMessageResponse.java
- src/main/java/capstone/facefriend/chat/service/dto/chatroom/ChatRoomOpenResponse.java
- src/main/java/capstone/facefriend/chat/service/dto/heart/GetSendHeartResponse.java
- src/main/java/capstone/facefriend/chat/service/dto/heart/SendHeartRequest.java
- src/main/java/capstone/facefriend/chat/service/dto/heart/SendHeartResponse.java
- src/main/java/capstone/facefriend/chat/service/dto/message/GetMessageResponse.java
- src/main/java/capstone/facefriend/chat/service/dto/message/MessageListResponse.java
- src/main/java/capstone/facefriend/chat/service/dto/message/MessageResponse.java
> #56 
- 메시지 기록 페이지네이션
- 채팅방 입장 정보 관리
- 애플리케이션 구동 정보 관리
- 소켓 연결을 안했을 때 오는 메시지 관리
api에 대한 문서화 내용은 노션 참고
https://www.notion.so/stomp-b72273dde25a4943b3b65c78e103ca91?pvs=4
> [Feat/Refactor] 채팅 부가기능 API 작성

- src/main/java/capstone/facefriend/member/domain/analysisInfo/AnalysisInfo.java
> 디버깅 : 필드명 수정
> 디버깅 : 필드명 수정
> 디버깅 : 필드명 수정
> 디버깅 : 필드명 수정
> 디버깅 : 필드명 수정
> fix: 필드명 수정

- src/main/java/capstone/facefriend/member/service/AnalysisInfoService.java
- src/main/java/capstone/facefriend/member/service/MemberService.java
> fix: getter 수정

- src/main/java/capstone/facefriend/auth/config/AuthConfig.java
> feat: include path pattern

- src/main/java/capstone/facefriend/chat/service/MessageService.java
- exception message 전달 수정
- stomp에서 exception이 터지면, http porotocol로 가기 때문에 Socekt으로 메시지가 오지 않습니다.
- 이를 고치기 위해서 프론트로 메시지를 보내고 exception을 던져서 서버에서도 에러를 확인하고 프론트에서도 socket으로 이 정보를 받을 수 있도록 구현했습니다.
> Refactor: Exception handling 서버에서만 예외를 처리하는 게 아니라 stomp로 이를 전송

- src/main/java/capstone/facefriend/chat/controller/MessageController.java
- src/main/java/capstone/facefriend/chat/service/MessageService.java
- 대화 요청 관련 로직에서 프론트에서 체크를 위한 response를 전달하는 코드 추가
> Refactor: 성공에 대한 response 필요로 코드 리팩토링

- src/main/java/capstone/facefriend/chat/service/MessageService.java
> Refactor: MessageSize 수정

- src/main/java/capstone/facefriend/resume/service/ResumeService.java
> fix: resume images put size 0 디버그

- src/main/java/capstone/facefriend/chat/controller/MessageController.java
> Refactor: message list 요청 http method get에서 post로

- src/main/java/capstone/facefriend/chat/service/MessageService.java
- src/main/java/capstone/facefriend/resume/controller/ResumeController.java
- src/main/java/capstone/facefriend/resume/domain/ResumeRepositoryCustom.java
- src/main/java/capstone/facefriend/resume/domain/ResumeRepositoryImpl.java
- src/main/java/capstone/facefriend/resume/service/ResumeService.java
> fix: sender, receiver 에 따라 faceInfoByLevel 다르게 반환

- src/main/java/capstone/facefriend/chat/service/MessageService.java
- src/main/java/capstone/facefriend/chat/service/RedisSubscriber.java
- src/main/java/capstone/facefriend/resume/domain/ResumeRepositoryImpl.java
> fix: 버그 픽스

- src/main/java/capstone/facefriend/chat/aop/ChatAop.java
- src/main/java/capstone/facefriend/chat/service/ChatRoomService.java
이미지 가중치 부여 시점 세분화
이미지 가중치 부여 시점 세분화
없음
없음
없음
> feat: 이미지 가중치 부여 시점 세분화

- src/main/java/capstone/facefriend/chat/aop/ChatAop.java
- src/main/java/capstone/facefriend/chat/service/ChatRoomService.java
- src/main/java/capstone/facefriend/chat/service/dto/chatroom/ChatRoomHeartResponse.java
- src/main/java/capstone/facefriend/chat/service/dto/chatroom/ChatRoomMessageResponse.java
- src/main/java/capstone/facefriend/chat/service/dto/chatroom/ChatRoomOpenResponse.java
- chatroom list에서 level에 맞는 이미지를 띄울 수 있도록 수정
> [Refactor] roomlist에서 level에 맞는 상대방 이미지

- front/pages/BottomNavigationPage.tsx
- front/pages/Friends.tsx
- front/pages/SelfProduce.tsx
- FE
- bottom navigation style 수정
- profile tab에서 자신의 이미지 보여주게 수정
> bottom navigation style 수정

- src/main/java/capstone/facefriend/chat/aop/ChatAop.java
@After 로 가중치 이미지 로딩시점 변경
@After 로 가중치 이미지 로딩시점 변경
없음 
없음 
없음
> feat: @After 로 가중치 이미지 로딩시점 변경

- src/main/java/capstone/facefriend/chat/service/MessageService.java
> Refactor: Response 수정

- src/main/java/capstone/facefriend/chat/config/RedisConfig.java
- src/main/java/capstone/facefriend/chat/controller/ChatRoomController.java
- src/main/java/capstone/facefriend/chat/service/ChatRoomService.java
- src/main/java/capstone/facefriend/chat/service/MessageService.java
- src/main/java/capstone/facefriend/chat/service/RedisSubscriber.java
- 불필요한 코드 정리
- 안 쓰게 된 api  code 정리
- ObjectMapper 경고 fix
> [Refactor] Chat api 불필요 코드 삭제 및 경고 fix

- src/main/java/capstone/facefriend/member/controller/AnalysisInfoController.java
- src/main/java/capstone/facefriend/member/service/AnalysisInfoService.java
> fix: analysis response 수정

- src/main/java/capstone/facefriend/DummyInitializer.java
- src/main/java/capstone/facefriend/chat/service/ChatRoomService.java
> refactor: leftroom logic 수정

- index.html
> chore: git pages

- src/main/java/capstone/facefriend/chat/aop/ChatAop.java
> refactor: 이미지 마스크 레벨 기준 상향으로 인한 리팩터링

- back/src/main/java/capstone/facefriend/chat/controller/MessageController.java
- back/src/main/java/capstone/facefriend/chat/controller/interceptor/FilterChannelInterceptor.java
> refactor: 삭제되었던 파일 원복
